### PR TITLE
Added version 5.9.6

### PR DESCRIPTION
**Pull request by WickedMaster**
Latest version

### CODE REVIEW

**Comment by IgorYbema** [comment]
this repo is not used anymore for production

**Comment by TimelessNL** [comment]
@IgorYbema maybe it's better to mention this in the readme. Otherwise people might still use this script while there is a newer version somewhere else.

This repo was still the first hit on google for me. And I had to browse the forums to find the [new repo](https://github.com/ToonSoftwareCollective/update-rooted) :P

**Comment by IgorYbema** [comment]
Good point. However the script in this older repo will still auto-update on first run to download from the new repo.
Though I'll think about adding a note in the README :-)

**Comment by TimelessNL** [comment]
But only if the user answers that question with yes. If they downloaded the file from here they might think they have the newest version already. :)

But still that counts for all the other forks ofcourse. But since 'ToonSoftwareCollactive' is forked from this repo it may seem like this is the base and thus the newest version. Normally it's the other way around with forked repos.

**Pull request closed without merging**
